#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
bundle exec htmlproofer --alt-ignore '/.*/' --http-status-ignore "999" _site --url-ignore "#installing-presto-on-hdinsight"
